#ifndef BLOCK_SIZE_H
#define BLOCK_SIZE_H

#define BLOCK_SIZE 64
#define N_TASKS_PER_PACK_SELF 16
#define N_TASKS_BUNDLE_SELF 4

#define BLOCK_SIZE_PAIR 64
#define N_TASKS_PER_PACK_PAIR 4096
#define N_TASKS_BUNDLE_PAIR 1024

#endif  // BLOCK_SIZE_H
